on: 
  pull_request: 
    types:
      - closed

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: okteto/login@latest
      with:
        url: ${{ secrets.OKTETO_URL }}
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Destroy namespace
      uses: okteto/delete-namespace@latest
      with:
        namespace: preview-pr-${{ github.event.number }}
