on: 
  pull_request: 
    types:
      - closed

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: okteto/login@master
      with:
        url: ${{ secrets.OKTETO_URL }}
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Destroy namespace
      uses: okteto/delete-namespace@master
      with:
        name: pr-${{ github.event.number }}
